utils::globalVariables(c("Animal.tracked", "Dist.travel", "Loc.type"))
utils::globalVariables(c("Latitude", "Longitude", "MAP", "aes", "Transmitter", "labs"))
utils::globalVariables(c("study.data"))
utils::globalVariables(c("Check", "spatial.check"))
utils::globalVariables(c("stop", "breaks", "timeframe", "debug", "verbose", "Timestamp"))